# Generated by Django 4.2 on 2025-08-17 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewflow', '0012_alter_process_data_alter_task_data'),
        ('ticketflow', '0013_businessunit_control_controlfactor_risk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='viewflow.process')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='ticketflow.risk')),
            ],
            options={
                'abstract': False,
            },
            bases=('viewflow.process',),
        ),
    ]
