# Generated by Django 4.2 on 2025-08-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0015_remove_control_created_by_remove_control_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='slug',
            field=models.SlugField(blank=True, help_text="Stable identifier (e.g., 'risk', 'control'). Auto-filled from name if blank.", max_length=64, null=True, unique=True),
        ),
    ]
