# Generated by Django 4.2 on 2025-08-20 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0016_form_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketprocess',
            name='ref_id',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated reference like RISK-0001 or CTRL-0001', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='FormCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_seq', models.PositiveIntegerField(default=1)),
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counter', to='ticketflow.form')),
            ],
        ),
    ]
