# Generated by Django 4.2 on 2025-08-25 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticketflow', '0017_ticketprocess_ref_id_formcounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='0-based order in the flow')),
                ('title', models.CharField(max_length=120)),
                ('role_group', models.CharField(choices=[('RR', 'Risk Representative'), ('RC', 'Risk Champion'), ('RA', 'Risk Approver'), ('CRO', 'CRO')], max_length=10)),
                ('allow_reject', models.BooleanField(default=True)),
                ('end_on_reject', models.BooleanField(default=False, help_text='If rejected here, flow ends')),
                ('notify_emails', models.TextField(blank=True, help_text='Comma-separated emails')),
                ('auto_claim', models.BooleanField(default=True, help_text='Auto claim task for correct role on open')),
                ('form', models.ForeignKey(blank=True, help_text='Optional form override for this step; if empty uses process.form', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketflow.form')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ticketflow.workflowtemplate')),
            ],
            options={
                'ordering': ['template', 'position'],
                'unique_together': {('template', 'position')},
            },
        ),
        migrations.CreateModel(
            name='ProcessStepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('decision', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('acted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_logs', to='ticketflow.ticketprocess')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketflow.workflowstep')),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketflow.workflowtemplate')),
            ],
            options={
                'ordering': ['process_id', 'index', 'acted_at'],
            },
        ),
    ]
