# Generated by Django 4.2 on 2025-08-31 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0019_workflowrole_userworkflowrole'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workflowstep',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='workflowstep',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='workflowtemplate',
            name='slug',
        ),
        migrations.AddField(
            model_name='workflowstep',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketflow.workflowrole'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='auto_claim',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='end_on_reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketflow.form'),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workflowstep',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='workflowtemplate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='allow_reject',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='notify_emails',
        ),
        migrations.RemoveField(
            model_name='workflowstep',
            name='role_group',
        ),
    ]
