# Generated by Django 4.2 on 2025-08-31 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketflow', '0020_alter_workflowstep_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicTicketProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.CharField(blank=True, editable=False, help_text='Auto-generated reference like RISK-0001 or CTRL-0001', max_length=50, null=True, unique=True)),
                ('ticket_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ticketflow.form')),
            ],
        ),
    ]
